//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Casillas()
        {
            this.DATReporteCasilla = new HashSet<DATReporteCasilla>();
        }
    
        public int IdCasilla { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> distrito { get; set; }
        public Nullable<decimal> municipio { get; set; }
        public string nmunicipio { get; set; }
        public Nullable<decimal> seccion { get; set; }
        public Nullable<decimal> localidad { get; set; }
        public string nlocalidad { get; set; }
        public Nullable<decimal> manzana { get; set; }
        public string casilla { get; set; }
        public string domicilio { get; set; }
        public string ubicacion { get; set; }
        public string referencia { get; set; }
        public string logitud { get; set; }
        public string latitud { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<int> IdDistritoFederal { get; set; }
        public int IdEncarte { get; set; }
        public int IdTipoCasilla { get; set; }
        public Nullable<int> CAMBIO { get; set; }
        public string ESTATUS2018 { get; set; }
    
        public virtual CATDistritoFederal CATDistritoFederal { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        public virtual CATSecciones CATSecciones { get; set; }
        public virtual CATTipoCasilla CATTipoCasilla { get; set; }
        public virtual Encarte Encarte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATReporteCasilla> DATReporteCasilla { get; set; }
    }
}
