//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATDistritoFederal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATDistritoFederal()
        {
            this.Casillas = new HashSet<Casillas>();
            this.DATPersonas = new HashSet<DATPersonas>();
            this.CATSecciones = new HashSet<CATSecciones>();
            this.DATEncuestas = new HashSet<DATEncuestas>();
            this.DATNoticias = new HashSet<DATNoticias>();
            this.DATNotificaciones = new HashSet<DATNotificaciones>();
            this.Territorio = new HashSet<Territorio>();
        }
    
        public int IdDistritoFederal { get; set; }
        public int DistritoFederal { get; set; }
        public int IdEstado { get; set; }
        public string Cabecera { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public int IdEncarte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Casillas> Casillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATPersonas> DATPersonas { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        public virtual Encarte Encarte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATSecciones> CATSecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATEncuestas> DATEncuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATNoticias> DATNoticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATNotificaciones> DATNotificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territorio> Territorio { get; set; }
    }
}
