//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatDistritoLocalDistritoFederal
    {
        public int IdEncarte { get; set; }
        public int IdEstado { get; set; }
        public int IdDistritoLocal { get; set; }
        public int IdDistritoFederal { get; set; }
        public int IdSeccion { get; set; }
    }
}
