//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATSecciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATSecciones()
        {
            this.Casillas = new HashSet<Casillas>();
            this.DATPersonas = new HashSet<DATPersonas>();
            this.DATCambioSeccion = new HashSet<DATCambioSeccion>();
            this.Territorio = new HashSet<Territorio>();
        }
    
        public int IdSeccion { get; set; }
        public int IdEstado { get; set; }
        public int IdMunicipio { get; set; }
        public int IdDistritoLocal { get; set; }
        public int IdDistritoFederal { get; set; }
        public int Seccion { get; set; }
        public int IdEncarte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Casillas> Casillas { get; set; }
        public virtual CATDistritoFederal CATDistritoFederal { get; set; }
        public virtual CATDistritoLocal CATDistritoLocal { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATPersonas> DATPersonas { get; set; }
        public virtual Encarte Encarte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATCambioSeccion> DATCambioSeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territorio> Territorio { get; set; }
    }
}
