//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATDomicilios
    {
        public System.Guid IdDomicilio { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string Colonia { get; set; }
        public int IdEstado { get; set; }
        public int IdMunicipio { get; set; }
        public string CP { get; set; }
        public System.Guid IdPersona { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
    
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        public virtual DATPersonas DATPersonas { get; set; }
    }
}
