//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATDetectados
    {
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombre { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string ClaveINE { get; set; }
        public string CURP { get; set; }
        public string NoEstado { get; set; }
        public string NoMunicipio { get; set; }
        public string Seccion { get; set; }
        public string Emision { get; set; }
        public string Vigencia { get; set; }
        public string OCR { get; set; }
        public string RegistroINE { get; set; }
        public string NoEmision { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.Guid> IdPadre { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public string Telefono { get; set; }
        public System.Guid IdPersona { get; set; }
    }
}
