//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATEncuestas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATEncuestas()
        {
            this.DATPreguntas = new HashSet<DATPreguntas>();
        }
    
        public System.Guid IdEncuesta { get; set; }
        public string Encuesta { get; set; }
        public int NoPregutas { get; set; }
        public System.DateTime Vigencia { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdDistritoFederal { get; set; }
        public Nullable<int> IdDistritoLocal { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> NotificacionEnviada { get; set; }
        public string InsertedUser { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> IdProceso { get; set; }
    
        public virtual CATDistritoFederal CATDistritoFederal { get; set; }
        public virtual CATDistritoLocal CATDistritoLocal { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATPreguntas> DATPreguntas { get; set; }
    }
}
