//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatGeolocalizacionNoProcesadas
    {
        public System.Guid IdPersona { get; set; }
        public string Message { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.Guid> IdDomicilio { get; set; }
    }
}
