//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATInvitados
    {
        public System.Guid IdInvitado { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.Guid> IdPersona { get; set; }
        public string CodigoInvitacion { get; set; }
        public Nullable<System.Guid> IdProceso { get; set; }
        public string App { get; set; }
        public Nullable<System.Guid> IdUser { get; set; }
    
        public virtual DATPersonas DATPersonas { get; set; }
    }
}
