//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATNoticias
    {
        public System.Guid IdNoticia { get; set; }
        public string Link { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdDistritoFederal { get; set; }
        public Nullable<int> IdDistritoLocal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Titulo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string InsertedUser { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> IdProceso { get; set; }
    
        public virtual CATDistritoFederal CATDistritoFederal { get; set; }
        public virtual CATDistritoLocal CATDistritoLocal { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
    }
}
