//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATProceso()
        {
            this.DATContacto = new HashSet<DATContacto>();
            this.DATReporteCasilla = new HashSet<DATReporteCasilla>();
            this.ProcesoUsuario = new HashSet<ProcesoUsuario>();
            this.Territorio = new HashSet<Territorio>();
        }
    
        public System.Guid IdProceso { get; set; }
        public string Nombre { get; set; }
        public bool Local { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public bool Archivado { get; set; }
        public bool Activo { get; set; }
        public string AddUser { get; set; }
        public System.DateTime AddDate { get; set; }
        public int IdEncarte { get; set; }
        public int IdEstado { get; set; }
    
        public virtual CATEstado CATEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATContacto> DATContacto { get; set; }
        public virtual Encarte Encarte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATReporteCasilla> DATReporteCasilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesoUsuario> ProcesoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territorio> Territorio { get; set; }
    }
}
