//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATPersonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATPersonas()
        {
            this.DATContacto = new HashSet<DATContacto>();
            this.DATDoctoPersona = new HashSet<DATDoctoPersona>();
            this.DATDomicilios = new HashSet<DATDomicilios>();
            this.DATInvitados = new HashSet<DATInvitados>();
            this.DATRespUsuario = new HashSet<DATRespUsuario>();
        }
    
        public System.Guid IdPersona { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombre { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string ClaveINE { get; set; }
        public string CURP { get; set; }
        public string NoEstado { get; set; }
        public string NoMunicipio { get; set; }
        public string Seccion { get; set; }
        public string Emision { get; set; }
        public string Vigencia { get; set; }
        public string OCR { get; set; }
        public string CIC { get; set; }
        public string RegistroINE { get; set; }
        public string NoEmision { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.Guid> IdPadre { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdDistritoFederal { get; set; }
        public Nullable<int> IdDistritoLocal { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<System.Guid> IdInvitado { get; set; }
        public Nullable<int> IdTipoCredencial { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public Nullable<System.Guid> IdProceso { get; set; }
        public Nullable<System.Guid> IdUserPadre { get; set; }
    
        public virtual CATDistritoFederal CATDistritoFederal { get; set; }
        public virtual CATDistritoLocal CATDistritoLocal { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        public virtual CATSecciones CATSecciones { get; set; }
        public virtual CATTipoCredencial CATTipoCredencial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATContacto> DATContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATDoctoPersona> DATDoctoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATDomicilios> DATDomicilios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATInvitados> DATInvitados { get; set; }
        public virtual UsersDeteccion UsersDeteccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATRespUsuario> DATRespUsuario { get; set; }
    }
}
