//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATRespUsuario
    {
        public System.Guid IdRespUsuario { get; set; }
        public System.Guid IdPregunta { get; set; }
        public Nullable<System.Guid> IdRespuesta { get; set; }
        public string RespAbierta { get; set; }
        public System.Guid IdPersona { get; set; }
    
        public virtual DATPersonas DATPersonas { get; set; }
        public virtual DATPreguntas DATPreguntas { get; set; }
        public virtual DATRespuestas DATRespuestas { get; set; }
    }
}
