//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATReporteCasilla
    {
        public System.Guid IdReporteCasilla { get; set; }
        public int IdCasilla { get; set; }
        public System.Guid IdProceso { get; set; }
        public int IdEstatusCasilla { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Comentario { get; set; }
        public string Usuario { get; set; }
    
        public virtual Casillas Casillas { get; set; }
        public virtual CATEstatusCasilla CATEstatusCasilla { get; set; }
        public virtual DATProceso DATProceso { get; set; }
    }
}
