//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDeteccionEntities : DbContext
    {
        public DBDeteccionEntities()
            : base("name=DBDeteccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casillas> Casillas { get; set; }
        public virtual DbSet<CATDistritoFederal> CATDistritoFederal { get; set; }
        public virtual DbSet<CATDistritoLocal> CATDistritoLocal { get; set; }
        public virtual DbSet<CATEstado> CATEstado { get; set; }
        public virtual DbSet<CATEstatusCasilla> CATEstatusCasilla { get; set; }
        public virtual DbSet<CATMunicipios> CATMunicipios { get; set; }
        public virtual DbSet<CATSecciones> CATSecciones { get; set; }
        public virtual DbSet<CATTipoCasilla> CATTipoCasilla { get; set; }
        public virtual DbSet<CATTipoContacto> CATTipoContacto { get; set; }
        public virtual DbSet<CATTipoCredencial> CATTipoCredencial { get; set; }
        public virtual DbSet<CATTipoDocumento> CATTipoDocumento { get; set; }
        public virtual DbSet<CATTipoPregunta> CATTipoPregunta { get; set; }
        public virtual DbSet<DATCambioSeccion> DATCambioSeccion { get; set; }
        public virtual DbSet<DATContacto> DATContacto { get; set; }
        public virtual DbSet<DATDoctoPersona> DATDoctoPersona { get; set; }
        public virtual DbSet<DATDomicilios> DATDomicilios { get; set; }
        public virtual DbSet<DATEncuestas> DATEncuestas { get; set; }
        public virtual DbSet<DatErrores> DatErrores { get; set; }
        public virtual DbSet<DatGeolocalizacionNoProcesadas> DatGeolocalizacionNoProcesadas { get; set; }
        public virtual DbSet<DATInvitados> DATInvitados { get; set; }
        public virtual DbSet<DATNoticias> DATNoticias { get; set; }
        public virtual DbSet<DATNotificaciones> DATNotificaciones { get; set; }
        public virtual DbSet<DATPersonas> DATPersonas { get; set; }
        public virtual DbSet<DatPersonasGeolocalizacion> DatPersonasGeolocalizacion { get; set; }
        public virtual DbSet<DATPreguntas> DATPreguntas { get; set; }
        public virtual DbSet<DATProceso> DATProceso { get; set; }
        public virtual DbSet<DATReporteCasilla> DATReporteCasilla { get; set; }
        public virtual DbSet<DATRespuestas> DATRespuestas { get; set; }
        public virtual DbSet<DATRespUsuario> DATRespUsuario { get; set; }
        public virtual DbSet<Encarte> Encarte { get; set; }
        public virtual DbSet<ProcesoUsuario> ProcesoUsuario { get; set; }
        public virtual DbSet<Territorio> Territorio { get; set; }
        public virtual DbSet<UsersDeteccion> UsersDeteccion { get; set; }
        public virtual DbSet<CatDistritoFederalDistritoLocal> CatDistritoFederalDistritoLocal { get; set; }
        public virtual DbSet<CatDistritoFederalMunicipio> CatDistritoFederalMunicipio { get; set; }
        public virtual DbSet<CatDistritoLocalDistritoFederal> CatDistritoLocalDistritoFederal { get; set; }
        public virtual DbSet<CatDistritoLocalMunicipio> CatDistritoLocalMunicipio { get; set; }
        public virtual DbSet<DATDetectados> DATDetectados { get; set; }
    }
}
