//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encarte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encarte()
        {
            this.Casillas = new HashSet<Casillas>();
            this.CATDistritoFederal = new HashSet<CATDistritoFederal>();
            this.CATDistritoLocal = new HashSet<CATDistritoLocal>();
            this.CATSecciones = new HashSet<CATSecciones>();
            this.DATCambioSeccion = new HashSet<DATCambioSeccion>();
            this.DATProceso = new HashSet<DATProceso>();
        }
    
        public int IdEncarte { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
        public System.DateTime ModDate { get; set; }
        public string ModUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Casillas> Casillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATDistritoFederal> CATDistritoFederal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATDistritoLocal> CATDistritoLocal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATSecciones> CATSecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATCambioSeccion> DATCambioSeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATProceso> DATProceso { get; set; }
    }
}
