//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territorio
    {
        public int IdTerritorio { get; set; }
        public System.Guid IdProceso { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdDistritoFederal { get; set; }
        public Nullable<int> IdDistritoLocal { get; set; }
        public Nullable<int> IdSeccion { get; set; }
    
        public virtual CATDistritoFederal CATDistritoFederal { get; set; }
        public virtual CATDistritoLocal CATDistritoLocal { get; set; }
        public virtual CATEstado CATEstado { get; set; }
        public virtual CATMunicipios CATMunicipios { get; set; }
        public virtual CATSecciones CATSecciones { get; set; }
        public virtual DATProceso DATProceso { get; set; }
    }
}
