//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecciones.Models.DBSMovilizacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDeteccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersDeteccion()
        {
            this.DATPersonas = new HashSet<DATPersonas>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string salt { get; set; }
        public Nullable<bool> isRegister { get; set; }
        public string Telefono { get; set; }
        public string token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATPersonas> DATPersonas { get; set; }
    }
}
