//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deteccion.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deteccion.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se registró? Iniciar sesión ahora.
        /// </summary>
        internal static string ButtonAlreadyUserLoginNow {
            get {
                return ResourceManager.GetString("ButtonAlreadyUserLoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese un correo válido.
        /// </summary>
        internal static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quiere cambiar su contraseña?.
        /// </summary>
        internal static string LabelChangePassword {
            get {
                return ResourceManager.GetString("LabelChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidó su contraseña?.
        /// </summary>
        internal static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se preocupe, escriba aquí su correo electrónico y lo recuperaremos por usted..
        /// </summary>
        internal static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su contraseña anterior y la nueva.
        /// </summary>
        internal static string LabelInputPassword {
            get {
                return ResourceManager.GetString("LabelInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión usando correo y contraseña..
        /// </summary>
        internal static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la información que se le pide.
        /// </summary>
        internal static string LabelRegisterGetCode {
            get {
                return ResourceManager.GetString("LabelRegisterGetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrese ahora para tener acceso a la App..
        /// </summary>
        internal static string LabelRegisterNow {
            get {
                return ResourceManager.GetString("LabelRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrese ahora para tener acceso a la App..
        /// </summary>
        internal static string LabelRegisterNowAndEnjoy {
            get {
                return ResourceManager.GetString("LabelRegisterNowAndEnjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar su contraseña ahora.
        /// </summary>
        internal static string LabelRegisterPassword {
            get {
                return ResourceManager.GetString("LabelRegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        internal static string PageTitleAddress {
            get {
                return ResourceManager.GetString("PageTitleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio INE.
        /// </summary>
        internal static string PageTitleAddressINE {
            get {
                return ResourceManager.GetString("PageTitleAddressINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticia.
        /// </summary>
        internal static string PageTitleArticleDetail {
            get {
                return ResourceManager.GetString("PageTitleArticleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmados.
        /// </summary>
        internal static string PageTitleConfirmed {
            get {
                return ResourceManager.GetString("PageTitleConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactos.
        /// </summary>
        internal static string PageTitleContactsList {
            get {
                return ResourceManager.GetString("PageTitleContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener Credenciales.
        /// </summary>
        internal static string PageTitleGetCredentials {
            get {
                return ResourceManager.GetString("PageTitleGetCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitados.
        /// </summary>
        internal static string PageTitleGuests {
            get {
                return ResourceManager.GetString("PageTitleGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitaciones.
        /// </summary>
        internal static string PageTitleInvitations {
            get {
                return ResourceManager.GetString("PageTitleInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuestas.
        /// </summary>
        internal static string PageTitleNavigationPollsList {
            get {
                return ResourceManager.GetString("PageTitleNavigationPollsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticias.
        /// </summary>
        internal static string PageTitleNews {
            get {
                return ResourceManager.GetString("PageTitleNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de Privacidad.
        /// </summary>
        internal static string PageTitleNoticePrivacy {
            get {
                return ResourceManager.GetString("PageTitleNoticePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        internal static string PageTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurperar Contraseña.
        /// </summary>
        internal static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar el Estado.
        /// </summary>
        internal static string PageTitleSelectState {
            get {
                return ResourceManager.GetString("PageTitleSelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la credencial.
        /// </summary>
        internal static string PageTitleSelectTypeCredential {
            get {
                return ResourceManager.GetString("PageTitleSelectTypeCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string PageTitleSignUp {
            get {
                return ResourceManager.GetString("PageTitleSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar su Contraseña.
        /// </summary>
        internal static string PageTitleSignUpPassword {
            get {
                return ResourceManager.GetString("PageTitleSignUpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        internal static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detección.
        /// </summary>
        internal static string PageTitleTab {
            get {
                return ResourceManager.GetString("PageTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuestas.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string StringAccept {
            get {
                return ResourceManager.GetString("StringAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        internal static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        internal static string StringChangePassword {
            get {
                return ResourceManager.GetString("StringChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string StringCode {
            get {
                return ResourceManager.GetString("StringCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Validación.
        /// </summary>
        internal static string StringCodeValidation {
            get {
                return ResourceManager.GetString("StringCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string StringContinue {
            get {
                return ResourceManager.GetString("StringContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Actual.
        /// </summary>
        internal static string StringCurrentPassword {
            get {
                return ResourceManager.GetString("StringCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        internal static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string StringNewPassword {
            get {
                return ResourceManager.GetString("StringNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes.
        /// </summary>
        internal static string StringNotes {
            get {
                return ResourceManager.GetString("StringNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso de Privacidad.
        /// </summary>
        internal static string StringNoticePrivacy {
            get {
                return ResourceManager.GetString("StringNoticePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notification.
        /// </summary>
        internal static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string StringPhone {
            get {
                return ResourceManager.GetString("StringPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PHOTOS.
        /// </summary>
        internal static string StringPhotos {
            get {
                return ResourceManager.GetString("StringPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string StringRegister {
            get {
                return ResourceManager.GetString("StringRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Encuesta.
        /// </summary>
        internal static string StringSendPoll {
            get {
                return ResourceManager.GetString("StringSendPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse!.
        /// </summary>
        internal static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtotal.
        /// </summary>
        internal static string StringSubtotal {
            get {
                return ResourceManager.GetString("StringSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        internal static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string StringTotal {
            get {
                return ResourceManager.GetString("StringTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba su respuesta....
        /// </summary>
        internal static string TypeYourAnswer {
            get {
                return ResourceManager.GetString("TypeYourAnswer", resourceCulture);
            }
        }
    }
}
