//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilizacion.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movilizacion.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese un correo válido.
        /// </summary>
        internal static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quiere cambiar su contraseña?.
        /// </summary>
        internal static string LabelChangePassword {
            get {
                return ResourceManager.GetString("LabelChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidó su contraseña?.
        /// </summary>
        internal static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se preocupe, escriba aquí su correo electrónico y lo recuperaremos por usted..
        /// </summary>
        internal static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su contraseña anterior y la nueva.
        /// </summary>
        internal static string LabelInputPassword {
            get {
                return ResourceManager.GetString("LabelInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicie sesión con su usuario y contraseña..
        /// </summary>
        internal static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        internal static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráficas.
        /// </summary>
        internal static string PageTilteGraphics {
            get {
                return ResourceManager.GetString("PageTilteGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticias.
        /// </summary>
        internal static string PageTitleArticlesClassicView {
            get {
                return ResourceManager.GetString("PageTitleArticlesClassicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectados.
        /// </summary>
        internal static string PageTitleChatMain {
            get {
                return ResourceManager.GetString("PageTitleChatMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        internal static string PageTitleContactsList {
            get {
                return ResourceManager.GetString("PageTitleContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuestas.
        /// </summary>
        internal static string PageTitleEncuestas {
            get {
                return ResourceManager.GetString("PageTitleEncuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitados.
        /// </summary>
        internal static string PageTitleGuests {
            get {
                return ResourceManager.GetString("PageTitleGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticias.
        /// </summary>
        internal static string PageTitleNews {
            get {
                return ResourceManager.GetString("PageTitleNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticia.
        /// </summary>
        internal static string PageTitleNewsDetail {
            get {
                return ResourceManager.GetString("PageTitleNewsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuestas.
        /// </summary>
        internal static string PageTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        internal static string PageTitleNotifications2 {
            get {
                return ResourceManager.GetString("PageTitleNotifications2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Contraseña.
        /// </summary>
        internal static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuestas.
        /// </summary>
        internal static string PageTitlePolls {
            get {
                return ResourceManager.GetString("PageTitlePolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casillas.
        /// </summary>
        internal static string PageTitleStalls {
            get {
                return ResourceManager.GetString("PageTitleStalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        internal static string StringChangePassword {
            get {
                return ResourceManager.GetString("StringChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicaciones.
        /// </summary>
        internal static string StringContacts {
            get {
                return ResourceManager.GetString("StringContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Actual.
        /// </summary>
        internal static string StringCurrentPassword {
            get {
                return ResourceManager.GetString("StringCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC.
        /// </summary>
        internal static string StringCVC {
            get {
                return ResourceManager.GetString("StringCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectados.
        /// </summary>
        internal static string StringDetected {
            get {
                return ResourceManager.GetString("StringDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicaciones.
        /// </summary>
        internal static string StringLocations {
            get {
                return ResourceManager.GetString("StringLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectados.
        /// </summary>
        internal static string StringMessages {
            get {
                return ResourceManager.GetString("StringMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña.
        /// </summary>
        internal static string StringNewPassword {
            get {
                return ResourceManager.GetString("StringNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas.
        /// </summary>
        internal static string StringPersons {
            get {
                return ResourceManager.GetString("StringPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casillas.
        /// </summary>
        internal static string StringStalls {
            get {
                return ResourceManager.GetString("StringStalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string StringTotal {
            get {
                return ResourceManager.GetString("StringTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        internal static string StringWelcomeToGrial {
            get {
                return ResourceManager.GetString("StringWelcomeToGrial", resourceCulture);
            }
        }
    }
}
